In [2]:
''' Multiclass classification using Deep Neural Networks: Example: Use the OCR letter
recognition datasethttps://archive.ics.uci.edu/ml/datasets/letter+recognition
'''

' Multiclass classification using Deep Neural Networks: Example: Use the OCR letter\nrecognition datasethttps://archive.ics.uci.edu/ml/datasets/letter+recognition\n'

In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler,LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [10]:
df=pd.read_csv('letter-recognition.data',header=None)

In [11]:
df.head()

  0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0  T   2   8   3   5   1   8  13   0   6   6  10   8   0   8   0   8
1  I   5  12   3   7   2  10   5   5   4  13   3   9   2   8   4  10
2  D   4  11   6   8   6  10   6   2   6  10   3   7   3   7   3   9
3  N   7  11   6   6   3   5   9   4   6   4   4  10   6  10   2   8
4  G   2   1   3   1   1   8   6   6   6   6   5   9   1   7   5  10

In [12]:
df.describe()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [13]:
df.tail()

      0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
19995  D   2   2   3   3   2   7   7   7   6   6   6   4   2   8   3   7
19996  C   7  10   8   8   4   4   8   6   9  12   9  13   2   9   3   7
19997  T   6   9   6   7   5   6  11   3   7  11   9   5   2  12   2   4
19998  S   2   3   4   2   1   8   7   2   6  10   6   8   1   9   5   8
19999  A   4   9   6   6   2   9   5   3   1   8   1   8   2   7   2   8

In [14]:
df.dtypes

0     object
1      int64
2      int64
3      int64
4      int64
5      int64
6      int64
7      int64
8      int64
9      int64
10     int64
11     int64
12     int64
13     int64
14     int64
15     int64
16     int64
dtype: object

In [15]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
dtype: int64

In [16]:
x=df.iloc[:,1:].values
y=df.iloc[:,0].values

In [17]:
le = LabelEncoder()
y=le.fit_transform(y)

In [18]:
y = to_categorical(y)  # One-hot encoding

In [20]:
scaler =  StandardScaler()
x=scaler.fit_transform(x)

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [24]:
model = Sequential()

In [26]:

model.add(Dense(64,activation='relu',input_shape=(16,)))
model.add(Dense(128,activation='relu'))
model.add(Dense(68,activation='relu'))
model.add(Dense(26,activation='softmax'))

In [27]:
model.compile(optimizer = 'adam',loss='categorical_crossentropy',
    metrics=['accuracy'])

In [28]:
history = model.fit(x_train,y_train,epochs=50,batch_size=32,validation_split=0.2)

Epoch 1/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.5564 - loss: 1.4460 - val_accuracy: 0.7281 - val_loss: 0.8382
Epoch 2/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.7945 - loss: 0.6523 - val_accuracy: 0.8234 - val_loss: 0.5477
Epoch 3/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8545 - loss: 0.4607 - val_accuracy: 0.8725 - val_loss: 0.4113
Epoch 4/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8817 - loss: 0.3601 - val_accuracy: 0.8859 - val_loss: 0.3603
Epoch 5/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9065 - loss: 0.2867 - val_accuracy: 0.8841 - val_loss: 0.3413
Epoch 6/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9201 - loss: 0.2416 - val_accuracy: 0.9013 - val_loss: 0.3136
Epoch 7/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9343 - loss: 0.1978 - val_accuracy: 0.9159 - val_loss: 0.2583
Epoch 8/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9384 - loss: 0.1812 - val_accuracy: 0.9153 - val_loss: 0.2760
Epoch 9/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9477 - loss: 0.1566 - val_accuracy: 0.9266 - val_loss: 0.2405
Epoch 10/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9518 - loss: 0.1445 - val_accuracy: 0.9297 - val_loss: 0.2120
Epoch 11/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9534 - loss: 0.1356 - val_accuracy: 0.9294 - val_loss: 0.2268
Epoch 12/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9595 - loss: 0.1134 - val_accuracy: 0.9150 - val_loss: 0.2622
Epoch 13/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9612 - loss: 0.1136 - val_accuracy: 0.9303 - val_loss: 0.2172
Epoch 14/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9605 - loss: 0.1082 - val_accuracy: 0.9337 - val_loss: 0.2034
Epoch 15/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9658 - loss: 0.0936 - val_accuracy: 0.9334 - val_loss: 0.1994
Epoch 16/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9666 - loss: 0.0966 - val_accuracy: 0.9344 - val_loss: 0.2107
Epoch 17/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9693 - loss: 0.0863 - val_accuracy: 0.9403 - val_loss: 0.1943
Epoch 18/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9730 - loss: 0.0740 - val_accuracy: 0.9441 - val_loss: 0.1890
Epoch 19/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9734 - loss: 0.0761 - val_accuracy: 0.9306 - val_loss: 0.2541
Epoch 20/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9726 - loss: 0.0805 - val_accuracy: 0.9294 - val_loss: 0.2409
Epoch 21/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9747 - loss: 0.0709 - val_accuracy: 0.9422 - val_loss: 0.1989
Epoch 22/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9766 - loss: 0.0704 - val_accuracy: 0.9463 - val_loss: 0.1815
Epoch 23/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9793 - loss: 0.0566 - val_accuracy: 0.9391 - val_loss: 0.2312
Epoch 24/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9792 - loss: 0.0613 - val_accuracy: 0.9438 - val_loss: 0.1850
Epoch 25/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9808 - loss: 0.0534 - val_accuracy: 0.9441 - val_loss: 0.1996
Epoch 26/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9819 - loss: 0.0573 - val_accuracy: 0.9356 - val_loss: 0.2457
Epoch 27/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9745 - loss: 0.0748 - val_accuracy: 0.9513 - val_loss: 0.1627
Epoch 28/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9860 - loss: 0.0407 - val_accuracy: 0.9488 - val_loss: 0.2306
Epoch 29/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9857 - loss: 0.0435 - val_accuracy: 0.9503 - val_loss: 0.1931
Epoch 30/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9819 - loss: 0.0550 - val_accuracy: 0.9366 - val_loss: 0.2411
Epoch 31/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9801 - loss: 0.0617 - val_accuracy: 0.9463 - val_loss: 0.1943
Epoch 32/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9810 - loss: 0.0527 - val_accuracy: 0.9513 - val_loss: 0.1782
Epoch 33/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9834 - loss: 0.0485 - val_accuracy: 0.9384 - val_loss: 0.2437
Epoch 34/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9820 - loss: 0.0563 - val_accuracy: 0.9350 - val_loss: 0.2450
Epoch 35/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9859 - loss: 0.0422 - val_accuracy: 0.9491 - val_loss: 0.1911
Epoch 36/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9890 - loss: 0.0352 - val_accuracy: 0.9484 - val_loss: 0.1977
Epoch 37/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9845 - loss: 0.0457 - val_accuracy: 0.9287 - val_loss: 0.2759
Epoch 38/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9873 - loss: 0.0371 - val_accuracy: 0.9375 - val_loss: 0.2470
Epoch 39/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9841 - loss: 0.0463 - val_accuracy: 0.9453 - val_loss: 0.2121
Epoch 40/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9809 - loss: 0.0563 - val_accuracy: 0.9569 - val_loss: 0.1592
Epoch 41/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9915 - loss: 0.0251 - val_accuracy: 0.9494 - val_loss: 0.1961
Epoch 42/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9837 - loss: 0.0519 - val_accuracy: 0.9422 - val_loss: 0.2375
Epoch 43/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9882 - loss: 0.0352 - val_accuracy: 0.9556 - val_loss: 0.1813
Epoch 44/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9908 - loss: 0.0327 - val_accuracy: 0.9413 - val_loss: 0.2456
Epoch 45/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9868 - loss: 0.0436 - val_accuracy: 0.9563 - val_loss: 0.1749
Epoch 46/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9909 - loss: 0.0335 - val_accuracy: 0.9509 - val_loss: 0.2027
Epoch 47/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9852 - loss: 0.0473 - val_accuracy: 0.9500 - val_loss: 0.2188
Epoch 48/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9886 - loss: 0.0349 - val_accuracy: 0.9453 - val_loss: 0.2263
Epoch 49/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9883 - loss: 0.0371 - val_accuracy: 0.9563 - val_loss: 0.1739
Epoch 50/50
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9887 - loss: 0.0351 - val_accuracy: 0.9478 - val_loss: 0.2139

In [30]:
loss, accuracy = model.evaluate(x_test, y_test)
print("Accuracy:", accuracy)

125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.9590 - loss: 0.1853
Accuracy: 0.9589999914169312